DROP TABLE IF EXISTS dragon;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS coordinates;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS dragon_character;
DROP TYPE IF EXISTS color;
